# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8aeeb50a8ccbd4c4e20c5126aba0a02a690634a14b85b4dd83c7e5a0d44522caa62ae0f080180bb8c4771e57358b52494a32b4397e591753d3a682fe4eea2d9

test:
  secret_key_base: f18bf4144165d8f63f0d13ea554f7457a160a4c3a32215b3130c8237e91063d47e3d3a7fe6da6c27a8ba0d884a48ef22ce12a4aad7a56a0d8d52f60f3f5b9f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
